### PR TITLE
Update on Reactifying GT; Not ready for merge

### PR DESCRIPTION
**Pull request by SonQHoang**
Finished skeleton of the nav bar with styling with the exception of the logout component.

Going to work through the song and search bar component next while I figure out how to connect react with rails for the logout.

### CODE REVIEW

**Comment by PatrickF1** [comment]
How come you keep opening and closing PRs? I like to keep all the context and conversations in the same PR unless you are abandoning the feature or changing the approach fundamentally

**Comment by SonQHoang** [comment]
Oh I wasn't aware that's what you wanted to use the pull request for / that is what pull requests are used for.

Since the updates weren't ready for a merge, I didn't want to leave it up, because in the past my projectmates would question why I had an ongoing pull request if I wasn't planning on merging. They always preferred to do code reviews instead over zoom and then make pull requsts for final checks. I'll keep the pull requests up moving forward.

**Comment by PatrickF1** [comment]
Ah I see, thanks for explaining. So in industry what we like to do is
- append WIP in the title
- some projects use a do-no-review label
- OR, ever since GitHub released the Draft PR feature, we just mark it as draft

Option 3 is most preferable for me and also probably most common I've seen. And I get notifications with every comment you leave so no need to open a new PR to get my attention.

Btw the reason NOT to open too many PRs is it makes browsing through the history of the repo much harder bc you end up with multiple PRs around the same thing and it's hard to tell which one is the one you want.

**Comment by SonQHoang** [comment]
Okay gotcha. Thanks for the heads up. I converted the PR into a draft.

**Pull request closed without merging**
